<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as El_Model;

class SocialAccount extends \App\Models\Model
{
    protected $fillable = ['user_id', 'provider_user_id', 'provider','token','profileUrl'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param $model
     */
    public function afterSave($model)
    {
        parent::afterSave($model); // TODO: Change the autogenerated stub
    }

}
